# Algebra Lineal Basica

## Vectores

In [2]:
import numpy as np

Definicion de vectores

In [3]:
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])

In [4]:
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


Transpuesta

In [6]:
new_vector = vector_row.T
print(new_vector)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]


Normas

In [7]:
from numpy.linalg import norm

In [9]:
norm_1 = norm(new_vector, 1)
print('L_1 es: %.1f'%norm_1)

norm_2 = norm(new_vector, 2)
print('L_2 es: %.1f'%norm_2)

norm_inf = norm(new_vector, np.inf)
print('L_inf es: %.1f'%norm_inf)

L_1 es: 15.0
L_2 es: 7.4
L_inf es: 5.0


Angulo enter dos vectores

In [10]:
from numpy import arccos, dot

In [11]:
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


Producto Cruz

In [12]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


Combinacion Lineal

In [13]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


## Matrices

Estructura de matrices y producto entre matrices

In [22]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3], [1, 2, 4]])
print(P)
print(Q)

np.dot(P, Q)
print(np.dot(P, Q))

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3]
 [1 2 4]]
[[ 9 20 31]
 [ 7 18 18]
 [10 30 15]]


Determinantes

In [23]:
from numpy.linalg import det

In [24]:
M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinante: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinante: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


Inversa

In [25]:
from numpy.linalg import inv

In [26]:
print('Inv M:\n', inv(M))
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(p):\n', det(P))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(p):
 0.0


Condicion y rango de matrices

In [27]:
from numpy.linalg import \
             cond, matrix_rank

In [29]:
A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Numero de Condicion:\n', cond(A))
print('Rango:\n', matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Matrix Aumentada:\n', A_y)

Numero de Condicion:
 4.048917339522305
Rango:
 3
Matrix Aumentada:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


## Siostemas de Ecuaciones Lineales

In [30]:
u = np.array([[4, 3, -5], 
              [0, -2.5, 2.5], 
              [0, 0, 12]])
l = np.array([[1, 0, 0], 
              [-0.5, 1, 0], 
              [2, -0.8, 1]])

print('LU=', np.dot(l, u))

LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


In [31]:
a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]

In [32]:
# Encontremos los coeficientes de la diagonal
diag = np.diag(np.abs(a)) 

In [33]:
# Encontremos la suma por filas sin la diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag 

In [34]:
if np.all(diag > off_diag):
    print('la matriz es diagonalmente dominante')
else:
    print('la matriz no es diagonalmente dominante')

la matriz es diagonalmente dominante


### Usemos el Metodo de Gauss-Seidel

In [38]:
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])

In [39]:
print('Resultados de Iteracion')
print(' k,    x1,    x2,    x3 ')
for k in range(1, 50):
    x1 = (14-3*x2+3*x3)/8
    x2 = (5+2*x1-5*x3)/(-8)
    x3 = (-8-3*x1-5*x2)/(-5)
    x = np.array([x1, x2, x3])
    #  verifiquemos si es mas pequenos que el limite
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    if dx < epsilon:
        converged = True
        print('Converge')
        break
        
    # actualizamos el valor de x
    x_old = x

if not converged:
    print('No converge, incrementamos el # de iteraciones')

Resultados de Iteracion
 k,    x1,    x2,    x3 
1, 1.7500, -1.0625, 1.5875
2, 2.7437, -0.3188, 2.9275
3, 2.9673, 0.4629, 3.8433
4, 3.0177, 1.0226, 4.4332
5, 3.0290, 1.3885, 4.8059
6, 3.0315, 1.6208, 5.0397
7, 3.0321, 1.7668, 5.1861
8, 3.0322, 1.8582, 5.2776
9, 3.0322, 1.9154, 5.3348
10, 3.0323, 1.9512, 5.3705
11, 3.0323, 1.9735, 5.3929
12, 3.0323, 1.9875, 5.4068
13, 3.0323, 1.9962, 5.4156
14, 3.0323, 2.0017, 5.4210
Converge


### Usemos la  Matriz Inversa

In [41]:
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


### Usando el solucionador de Numpy

In [42]:
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


### Usando descomposicion LU

In [43]:
from scipy.linalg import lu

In [44]:
P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


Veamos que pasa si utilizamos la matriz de permutacion P en A

In [45]:
print(np.dot(P, A))

[[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
